import '../core/network/api_helper.dart';
import '../core/network/api_utilities.dart';
import '../core/network/endpiont.dart';
import 'model.dart';

class Repo {
  final ApiHelper apiHelper;

  Repo(this.apiHelper);

  Future<NetworkResponse> getDelegates({
    required Autogenerated delegatesRequestBody,
  }) async {
    return apiHelper.apiCall<Autogenerated>(
      products,
      requestType: RequestType.get,
      sessionToken: "dummyToken",
      headers: {"Custom-Header": "CustomValue"},
      mapper: (json) => Autogenerated.fromJson(json),
    );
  }
}
