import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_application_1/ui/repo.dart';

import '../injection_container.dart';
import 'model.dart';

class ProductsScreen extends StatefulWidget {
  const ProductsScreen({super.key});

  @override
  State<ProductsScreen> createState() => _ProductsScreenState();
}

class _ProductsScreenState extends State<ProductsScreen> {
  late Future<List<Products>> productsFuture;
Repo  repo = sl<Repo>();

  @override
  void initState() {
    super.initState();
    productsFuture = fetchProducts();
  }

  Future<List<Products>> fetchProducts() async {
    final response = await repo.getDelegates(
      delegatesRequestBody: Autogenerated(),
    );

    if (response.isSuccess && response.data != null) {
      return response.data!.products ?? [];
    } else {

      return [];
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Products")),
      body: FutureBuilder<List<Products>>(
        future: productsFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: Text("Error: ${snapshot.error}"));
          }
          final products = snapshot.data ?? [];
          if (products.isEmpty) {
            return const Center(child: Text("No products found"));
          }
          return ListView.builder(
            itemCount: products.length,
            itemBuilder: (context, index) {
              final product = products[index];
              return Card(
                margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                child: ListTile(
                  leading: product.thumbnail != null
                      ? Image.network(
                    product.thumbnail!,
                    width: 50,
                    height: 50,
                    fit: BoxFit.cover,
                  )
                      : const Icon(Icons.image),
                  title: Text(product.title ?? 'No Title'),
                  subtitle: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(product.description ?? 'No Description'),
                      const SizedBox(height: 4),
                      Text("Price: \$${product.price ?? 0}"),
                      if (product.rating != null)
                        Row(
                          children: List.generate(
                            5,
                                (i) => Icon(
                              i < (product.rating?.round() ?? 0)
                                  ? Icons.star
                                  : Icons.star_border,
                              size: 16,
                              color: Colors.amber,
                            ),
                          ),
                        ),
                    ],
                  ),
                  isThreeLine: true,
                ),
              );
            },
          );
        },
      ),
    );
  }
}
